stages:
    osm_graph:
        cmd: python -m ahah.osm_graph
        deps:
            - data/raw/osm_pbf
        outs:
            - data/processed/osm/nodes.parquet
            - data/processed/osm/edges.parquet
    process_data:
        cmd: python -m ahah.process_data
        deps:
            - data/processed/osm/nodes.parquet
            - data/raw/postcodes
            - data/raw/retailcentrecentroids.gpkg
            - data/raw/nhs-dent-stat-eng-19-20-anx3-act.csv
        outs:
            - data/processed/postcodes.parquet
            - data/processed/retail.parquet
            - data/processed/dentists.parquet
    routing:
        cmd: python -m ahah.routing
        deps:
            - data/processed/osm/edges.parquet
            - data/processed/postcodes.parquet
            - data/processed/retail.parquet
            - data/processed/dentists.parquet
        outs:
            - data/out/retail_dist.csv
            - data/out/dentists_dist.csv
